train:
  id: csgo
  size: [320, 240]
num_actions: 39
path_data_low_res: /home/kristofe/Documents/Projects/wm_mariokart64/tracks/low_res
path_data_full_res: /home/kristofe/Documents/Projects/wm_mariokart64/tracks/full_res
keymap: csgo
