defaults:
  - _self_
  - env: csgo
  - agent: csgo
  - world_model_env: fast

hydra:
  job:
    chdir: True

wandb:
  mode: disabled
  project: null
  entity: null
  name: "ultra_quick_test"
  group: null
  tags: null
  notes: null

initialization:
  path_to_ckpt: null
  load_denoiser: True
  load_rew_end_model: True
  load_actor_critic: True

common:
  devices: all
  seed: null
  resume: False

checkpointing:
  save_agent_every: 1
  num_to_keep: 2

collection:
  train:
    num_envs: 1
    epsilon: 0.01
    num_steps_total: 100  # Very small
    first_epoch:
      min: 10  # Very small
      max: 20  # Very small
      threshold_rew: 10
    steps_per_epoch: 2  # Very small
  test:
    num_envs: 1
    num_episodes: 1  # Very small
    epsilon: 0.0
    num_final_episodes: 2  # Very small

static_dataset:
  path: ${env.path_data_low_res}
  ignore_sample_weights: True

training:
  should: True
  num_final_epochs: 1  # Just 1 epoch
  cache_in_ram: False
  num_workers_data_loaders: 1
  model_free: False
  compile_wm: False

evaluation:
  should: False  # Skip evaluation for ultra quick test

# Optimized logging for quick tests
logging:
  tensorboard_frequency: 1  # Log every epoch for quick tests
  image_frequency: 1  # Log images every epoch for quick tests
  wandb_frequency: 1  # Log to wandb every epoch

denoiser:
  training:
    num_autoregressive_steps: 1  # Very small
    start_after_epochs: 0
    steps_first_epoch: 2  # Very small
    steps_per_epoch: 2  # Very small
    sample_weights: null
    batch_size: 2  # Very small
    grad_acc_steps: 1  # Default for ultra quick test
    lr_warmup_steps: 1  # Very small
    max_grad_norm: 10.0

  optimizer:
    lr: 1e-4
    weight_decay: 1e-2
    eps: 1e-8
  
  sigma_distribution:
    _target_: models.diffusion.SigmaDistributionConfig
    loc: -1.2
    scale: 1.2
    sigma_min: 2e-3
    sigma_max: 20

upsampler:
  training:
    num_autoregressive_steps: 1
    start_after_epochs: 0
    steps_first_epoch: 1  # Very small
    steps_per_epoch: 1  # Very small
    sample_weights: null
    batch_size: 2  # Very small
    grad_acc_steps: 1  # Default for ultra quick test
    lr_warmup_steps: 1  # Very small
    max_grad_norm: 10.0

  optimizer: ${denoiser.optimizer}
  sigma_distribution: ${denoiser.sigma_distribution}
